Add the main key so it can be required with Browserify
I want to use lazysizes with Browserify. This resolves the issue that says "Uncaught Error: Cannot find module 'lazysizes'".